+incdir+rtl
+incdir+rtl/core
+incdir+rtl/bus
+incdir+rtl/periph
+incdir+rtl/debug
+incdir+tb/models
rtl/core/sisAlu.sv
rtl/core/sisCsr.sv
rtl/core/sisDecode.sv
rtl/core/sisDecompress.sv
rtl/core/sisPmp.sv
rtl/core/sisRegFile.sv
rtl/core/sisRvCore.sv
rtl/bus/sisAxiLiteM.sv
rtl/bus/sisMemFabric.sv
rtl/periph/sisClint.sv
rtl/periph/sisGpio.sv
rtl/periph/sisPlic.sv
rtl/periph/sisRam.sv
rtl/periph/sisRom.sv
rtl/periph/sisTimer.sv
rtl/periph/sisTohost.sv
rtl/periph/sisUart.sv
rtl/debug/sisDm.sv
rtl/debug/sisJtagDtm.sv
rtl/sisPlatformTop.sv
tb/models/sisAxiLiteSlave.sv
tb/models/tb_dummy_model.sv
tb/sv/sisTbTop.sv
