+incdir+third_party/uvm/src
+incdir+verification/uvm/vip/decompress
+incdir+verification/uvm/vip/tohost
+incdir+verification/uvm/vip/jtag
+incdir+verification/uvm/env
+incdir+verification/uvm/tests
+incdir+rtl
+incdir+rtl/core
+incdir+rtl/bus
+incdir+rtl/periph
+incdir+rtl/debug
+incdir+tb/models
-DASSERT
-DUVM_NO_DPI
-DCOMMERCIAL_SIM
third_party/uvm/src/uvm.sv
verification/uvm/vip/decompress/sis_decompress_if.sv
verification/uvm/vip/decompress/sis_decompress_pkg.sv
verification/uvm/vip/tohost/sis_tohost_if.sv
verification/uvm/vip/tohost/sis_tohost_pkg.sv
verification/uvm/vip/jtag/sis_jtag_if.sv
verification/uvm/vip/jtag/sis_jtag_pkg.sv
verification/uvm/env/sis_env_pkg.sv
verification/uvm/tests/sis_test_pkg.sv
rtl/core/sisAlu.sv
rtl/core/sisCsr.sv
rtl/core/sisDecode.sv
rtl/core/sisDecompress.sv
rtl/core/sisPmp.sv
rtl/core/sisRegFile.sv
rtl/core/sisRvCore.sv
rtl/bus/sisAxiLiteM.sv
rtl/bus/sisMemFabric.sv
rtl/periph/sisClint.sv
rtl/periph/sisGpio.sv
rtl/periph/sisPlic.sv
rtl/periph/sisRam.sv
rtl/periph/sisRom.sv
rtl/periph/sisTohost.sv
rtl/periph/sisUart.sv
rtl/debug/sisDm.sv
rtl/debug/sisJtagDtm.sv
rtl/sisPlatformTop.sv
tb/models/sisAxiLiteSlave.sv
tb/models/tb_dummy_model.sv
verification/uvm/tb/sis_uvm_platform_tb.sv
