+incdir+third_party/uvm/src
+incdir+verification/uvm/vip/decompress
+incdir+verification/uvm/env
+incdir+verification/uvm/tests
+incdir+rtl/core
-DASSERT
-DUVM_NO_DPI
-DCOMMERCIAL_SIM
third_party/uvm/src/uvm.sv
verification/uvm/vip/decompress/sis_decompress_if.sv
verification/uvm/vip/decompress/sis_decompress_pkg.sv
verification/uvm/vip/tohost/sis_tohost_if.sv
verification/uvm/vip/tohost/sis_tohost_pkg.sv
verification/uvm/env/sis_env_pkg.sv
verification/uvm/tests/sis_test_pkg.sv
rtl/core/sisDecompress.sv
verification/uvm/tb/sis_uvm_decompress_tb.sv
